<?php

namespace Adonai\Bundle\SudokuBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvioRepository extends EntityRepository
{
}